### ISSUE TITLE
Missing id from user table

### ISSUE THREAD

**Issue by dhararon** [jrobichaud/django-structlog#13]
Hi,

When you use a different name for primary key the app crash, example

```python
uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```
You need to get the primary key not the id in this [line](https://github.com/jrobichaud/django-structlog/blob/38bd7ffae04a20c26c4c890087148e3d86c06019/django_structlog/middlewares/request.py#L31)

SmileyChris:

> “id” is just the default primary key field, whereas “pk” is an alias to the field which is defined as the primary key.

**Comment by jrobichaud** [comment]
Ill change it, thanks for pointing that out.

**Comment by jrobichaud** [comment]
1.3.3 will be out in a few minutes with the fix.

**Comment by jrobichaud** [comment]
@dhararon 1.3.3 is out, it took longer since I forgot to tag the commit. 🤦‍♂ 

If this does not fix your issue please re-open the issue.

Relating your issue, for the moment it is not possible to customize the keys in metadata.

It will still logged as `user_id` and not as `user_uuid`. If it is a problem for you please open a different issue. 

I was considering adding the possibility of customizing all the keys. Ex: event names and metadata.
