### ISSUE TITLE
Add child_task_id and child_task_name to task_revoked log

### ISSUE THREAD

**Issue by badziyoussef** [jrobichaud/django-structlog#317]
To be able to know which task was revoked, it could be a good idea to bind child_task_id and child_task_name to task_revoked log

**Comment by jrobichaud** [comment]
Thanks for pointing that out.

The pre-release `6.0.0.dev3` is out on [pypi](https://pypi.org/project/django-structlog/6.0.0.dev3/) with the fix.

Since it is a pre-release you need to specify the version explicitly:

```bash
pip install django-structlog==6.0.0.dev3
```

Let me know if it works as you expected.

Take note the names are different than you requested. See: [task-event-metadata](https://django-structlog.readthedocs.io/en/latest/events.html#task-event-metadata)

I will release version 6.0.0 officially when python 3.12 will be officially out.

**Comment by badziyoussef** [comment]
> Thanks for pointing that out.
> 
> The pre-release `6.0.0.dev3` is out on [pypi](https://pypi.org/project/django-structlog/6.0.0.dev3/) with the fix.
> 
> Since it is a pre-release you need to specify the version explicitly:
> 
> ```bash
> pip install django-structlog==6.0.0.dev3
> ```
> 
> Let me know if it works as you expected.
> 
> Take note the names are different than you requested. See: [task-event-metadata](https://django-structlog.readthedocs.io/en/latest/events.html#task-event-metadata)
> 
> I will release version 6.0.0 when python 3.12 will be officially out.

I was expecting same keys on all logs to be able to automatise processing or filtering on them, but this solution is good aswell, thanks for the change

**Comment by jrobichaud** [comment]
`child_task_id` and `child_task_name`  are specific to the enqueue of task in a parent (request or another task). I could not bind `task_id` because we could be already in a task.

Revoked task is done in a worker's perspective where the task being executed is revoked. (or never had the chance to start).

`task_id` and `task` respectively seemed more appropriate in that perspective.

**Comment by badziyoussef** [comment]
> `child_task_id` and `child_task_name`  are specific to the enqueue of task in a parent (request or another task). I could not bind `task_id` in the enqueue because we could be already in a task.
> 
> Revoked task is done in a worker's perspective where the task being executed is revoked. (or never had the chance to start).
> 
> `task_id` and `task` respectively seemed more appropriate in that perspective.

very clear, thanks for the explanation.
