### ISSUE TITLE
Add type hinting and a `py.typed` marker file

### ISSUE THREAD

**Issue by j00bar** [jrobichaud/django-structlog#696]
It would be awesome to be able to use this library in projects that are type checked by mypy without having to add it to the ignores.

To do that, for the installable code, you'd need to type hint the arguments and return for each function and then touch a `py.typed` file in the module to alert mypy it's safe to use the annotations on the code itself.

**Comment by jrobichaud** [comment]
I have a stash on my computer where I started to work on the type definitions.

I'll completing it eventually.

**Comment by jrobichaud** [comment]
@j00bar, or anyone. 
I find a lot of reference/blog posts on how to integrate `mypy` in a *project*, but not much anything about integrating it in a *third party library* like `django-structlog`.

do you know:
- a good third party library that has type definition?
- any library that does it wrong any why?
- since `django-structlog` requires `django` and optionally `celery`. Should a third party library like `django-structlog` avoid using stubs like `django-stubs[compatible-mypy]` or `celery-types` respectively?
- any other recommendations?

**Comment by jrobichaud** [comment]
Good to know, some type definitions change depending of python's version, we have to support compatibility from 3.9 to 3.13: 

https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#useful-built-in-types

**Comment by jrobichaud** [comment]
@j00bar, please take a look at #697

**Comment by jrobichaud** [comment]
@j00bar make sure to use precisely `9.0.0.dev1`, I used `dev2` to test another pull request.
